// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3yrmJUY0cSVpfFMX0xBgZmWWbLU8Srus',
    appId: '1:815439497415:android:6740e9db39154fa2a1d6e2',
    messagingSenderId: '815439497415',
    projectId: 'planetaria-fbdbf',
    databaseURL: 'https://planetaria-fbdbf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'planetaria-fbdbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNlKdizJOx58kK4-B2o71cEljdBC-AbUU',
    appId: '1:815439497415:ios:3704883607bd297ea1d6e2',
    messagingSenderId: '815439497415',
    projectId: 'planetaria-fbdbf',
    databaseURL: 'https://planetaria-fbdbf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'planetaria-fbdbf.firebasestorage.app',
    iosBundleId: 'com.example.planetaria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAE8pkrfG3Tve-xfQyThPrIGU_YO9haTc',
    appId: '1:815439497415:web:edd7d95726018143a1d6e2',
    messagingSenderId: '815439497415',
    projectId: 'planetaria-fbdbf',
    authDomain: 'planetaria-fbdbf.firebaseapp.com',
    databaseURL: 'https://planetaria-fbdbf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'planetaria-fbdbf.firebasestorage.app',
    measurementId: 'G-PMTQ2PM5FK',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAE8pkrfG3Tve-xfQyThPrIGU_YO9haTc',
    appId: '1:815439497415:web:edd7d95726018143a1d6e2',
    messagingSenderId: '815439497415',
    projectId: 'planetaria-fbdbf',
    authDomain: 'planetaria-fbdbf.firebaseapp.com',
    databaseURL: 'https://planetaria-fbdbf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'planetaria-fbdbf.firebasestorage.app',
    measurementId: 'G-PMTQ2PM5FK',
  );

}